$(selector).hide()	//隐藏被选元素
$(selector).show()	//显示被选元素
$(selector).toggle()	//切换（在隐藏与显示之间）被选元素
$(selector).slideDown()	//向下滑动（显示）被选元素
$(selector).slideUp()	//向上滑动（隐藏）被选元素
$(selector).slideToggle()	//对被选元素切换向上滑动和向下滑动
$(selector).fadeIn()	//淡入被选元素
$(selector).fadeOut()	//淡出被选元素
$(selector).fadeTo()	//把被选元素淡出为给定的不透明度
$(selector).animate()	//对被选元素执行自定义动画